# rag/configs/retrieval/faiss_rerank.yaml
# Dense retrieval with E5 + cross-encoder reranker
# ------------------------------------------------

retrieval_method:            e5-base-v2
retrieval_topk:              10          # top-k that FAISS returns *before* rerank

index_path:                  indexes/balanced_grammar/e5_index/e5-base-v2_Flat.index
corpus_path:                 data/processed/balanced_grammar/balanced_500.jsonl
retrieval_model_path:        intfloat/e5-base-v2

retrieval_query_max_length:  64
retrieval_pooling_method:    mean
retrieval_use_fp16:          false
retrieval_batch_size:        32
use_sentence_transformer:    false
faiss_gpu:                   false

# ------- RERANKER (BI-ENCODER) note: Cross encoder kept crashing--------------
use_reranker: true

rerank_model_name:   e5-base-v2          # <- same family as dense encoder
rerank_model_path:   intfloat/e5-base-v2
rerank_pooling_method: mean
rerank_topk:         20
rerank_batch_size:   32
rerank_max_length:    256
rerank_use_fp16:     false      # keep cpu-friendly

# ---------- cache flags (still off) ------------------------------------------
instruction:           null
save_retrieval_cache:  false
use_retrieval_cache:   false
retrieval_cache_path:  null

device: cpu # optional; BI reranker works on cpu by default
