# The base directory where the processed datasets are stored.
input_data_dir: "data/processed"

# Common corpus size for this analysis run.
corpus_size: 50

# The base location for all output reports and visualisations.
# The script will create a subdirectory like /corpus_size_500 within this.
output_dir: "evaluation/corpus_analysis/visualisations"

# List of grammar profiles to analyse. They will all use the corpus_size above.
grammar_profiles:
  - name: "loose_grammar"
    adjective: "loose"
  - name: "balanced_grammar"
    adjective: "balanced"
  - name: "high_constraint_grammar"
    adjective: "high_constraint"