# Config for building the BM25 (sparse) index

# Path to the corpus you want to index
corpus_path: data/processed/balanced_grammar/balanced_500.jsonl

# Specify the retrieval method and where to save the index
retrieval_method: bm25
index_path: indexes/balanced_grammar/corpus_size_500



