# Config for building the E5 (dense) index

# Path to the corpus you want to index
corpus_path: data/processed/balanced_grammar/balanced_500.jsonl

# Specify the retrieval method and where to save the index
retrieval_method: e5-base-v2
index_path: indexes/balanced_grammar/corpus_size_500/e5