# configs/synthetic_dataset_creation/balanced_run.yaml

# Tells the loader which grammar "world" to use.
grammar_profile: "balanced_grammar"
ebnf_file: "loose_structures.ebnf"

# This entire block will be passed to the Planner
planner_config:
  name: "Balanced Grammar"

  # checks structural similarity - high value catches nearly identical plans
  plan_deduplication_threshold: 0.90
  # enforce a progressive sequence of points e.g. [7,7,11, 15]
  enforce_plan_points_progression: false
  # Add any other planner-specific rules for this profile here

# High-level run params
num: 100
outfile_template: "data/processed/balanced_grammar/balanced_{num}.jsonl"
seed: 43
log_skips: false

# Controls JSON output formatting. Set to a number (e.g., 4) for pretty-printing,
# or false for compact, single-line output.
json_indent: false

# Exhaustion / attempts
max_attempts_multiplier: 50.0
consecutive_dup_limit: 2500

# Exact dedup (hash)
dedup_by: plan     # plan | text | none

# Jaccard near-dup
jaccard_dedup: true
jaccard_ngram: 2
jaccard_threshold: 0.88
jaccard_window: 500

# Semantic near-dup
semantic_dedup: true
semantic_threshold: 0.93
semantic_model: sentence-transformers/all-MiniLM-L6-v2
semantic_device: null  # "cpu" | "cuda" | null for auto
