# configs/synthetic_dataset_creation/low_constraint_run.yaml

# Tells the loader which grammar "world" to use.
grammar_profile: "low_constraint_grammar"
ebnf_file: "loose_structures.ebnf"

# High-level run params
num: 5
outfile: data/processed/low_constraint_grammar/balanced_5.jsonl
seed: 43

# Controls JSON output formatting. Set to a number (e.g., 4) for pretty-printing,
# or false for compact, single-line output.
json_indent: false

# Exhaustion / attempts
max_attempts_multiplier: 50.0
consecutive_dup_limit: 2500

# Exact dedup (hash)
dedup_by: plan     # plan | text | none

# Jaccard near-dup
jaccard_dedup: true
jaccard_ngram: 2
jaccard_threshold: 0.88
jaccard_window: 500

# Semantic near-dup
semantic_dedup: true
semantic_threshold: 0.93
semantic_model: sentence-transformers/all-MiniLM-L6-v2
semantic_device: null  # "cpu" | "cuda" | null for auto


# maybe decreasing similarity threshold, encore_progression: false, ...