// Import and ignore whitespace globally
%import common.WS
%ignore WS

// The top-level rule
session: drill_session | conditioned_game_session | mix_session

// Rule definitions
drill_session: drill_45_5 | drill_45_6 | drill_60_5 | drill_60_6
drill_45_5: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK
drill_45_6: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK
drill_60_5: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK
drill_60_6: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK

conditioned_game_session: cg_45_3 | cg_45_4 | cg_60_4 | cg_60_5
cg_45_3: WARMUP_BLOCK CG_BLOCK CG_BLOCK
cg_45_4: WARMUP_BLOCK CG_BLOCK CG_BLOCK CG_BLOCK
cg_60_4: WARMUP_BLOCK CG_BLOCK CG_BLOCK CG_BLOCK
cg_60_5: WARMUP_BLOCK CG_BLOCK CG_BLOCK CG_BLOCK CG_BLOCK

mix_session: mix_45_5 | mix_45_6 | mix_60_5 | mix_60_6
mix_45_5: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK
mix_45_6: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK
mix_60_5: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK
mix_60_6: WARMUP_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK ACTIVITY_BLOCK

// Terminal definitions
WARMUP_BLOCK: "WARMUP_BLOCK"
ACTIVITY_BLOCK: "ACTIVITY_BLOCK"
CG_BLOCK: "CG_BLOCK"