# configs/retrieval/sparse_retriever.yaml

# --- Experiment Details ---
#query: "I need a 60-minute practice for an intermediate player to improve my counter drops."
query: "A need a 45min session to improve my counter drop"
retrieval_strategy: "sparse_only"

# --- Template Variables ---
template_vars:
  corpus_size: 10
  grammar_type: "balanced"
  # Used to generate the output filename
  strategy_name: "sparse_only"

# --- Core Paths ---
paths:
  corpus: "data/processed/{grammar_type}_grammar/{grammar_type}_{corpus_size}.jsonl"
  output: "data/results/{strategy_name}_{grammar_type}_{corpus_size}_results.jsonl"
  prompt_template_dir: "prompts/rag"

# --- Model & Pipeline Parameters ---
llm_model: "gpt-4o"
top_k: 30

# --- Sparse Retriever Parameters (BM25) ---
sparse_params:
  index_path: "indexes/{grammar_type}_grammar/corpus_size_{corpus_size}/bm25/bm25_index_{grammar_type}.pkl"
  k1: 1.2
  b: 0.85