name: CI
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: macos-14
    env:
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      KMP_DUPLICATE_LIB_OK: "TRUE"
      TOKENIZERS_PARALLELISM: "false"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Use 3.11 as specified in your initial CI logs

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # editable FlashRAG + runtime libs
          pip install -e third_party/flashrag faiss-cpu datasets PyYAML transformers sentence-transformers # Added sentence-transformers as it's needed for e5-base-v2

      - name: Prepare Corpus (my_kb.jsonl)
        # This runs src/corpus_tools.py to generate data/my_kb.jsonl
        # The script needs to be run from the project root.
        run: python src/corpus_tools.py
        working-directory: ${{ github.workspace }}

      - name: Build FAISS Index
        # This uses flashrag's index_builder.
        # Paths here are relative to the working-directory (github.workspace, which is the root of the cloned repo).
        run: |
          python3 -m flashrag.retriever.index_builder \
            --retrieval_method e5-base-v2 \
            --model_path intfloat/e5-base-v2 \
            --corpus_path data/my_kb.jsonl \
            --save_dir rag/indexes/my_kb \
            --faiss_type Flat
        working-directory: ${{ github.workspace }} # Ensure this command runs from the project root

      - name: Run unit tests
        # These tests are in 'rag/tests' and need to be run from 'rag' directory
        run: pytest -q
        working-directory: rag # Set the working directory to 'rag' for pytest to correctly resolve ROOT and config paths