name: CI
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: macos-14
    env:
      OMP_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      KMP_DUPLICATE_LIB_OK: "TRUE"
      TOKENIZERS_PARALLELISM: "false"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e third_party/flashrag
          pip install faiss-cpu datasets PyYAML pytest

      - name: Run unit tests
        run: pytest -q
